import ccxt from "ccxt";
import { STATUS_CODES } from "node:http";
import { describe, expect, it } from "vitest";
import { isRefusal, type Refusal } from "../../src/core/errors.ts";
import { venuesHere, type AvailabilityDeps } from "../../src/portfolio/live/availability.ts";
import { compareAcross, type CompareVenue } from "../../src/portfolio/live/compare.ts";
import { exploreAcross } from "../../src/portfolio/live/explore.ts";
import { guardClient, type ExchangeClient, type OpenExchange } from "../../src/portfolio/live/exchange.ts";
import { exchangeNo, exchangeTickers, holdBackMs, kalshiPublic, polymarketPublic, preIpoPublic, stockTokensPublic, type Listing, type PublicSource } from "../../src/portfolio/live/public-markets.ts";
import type { Reach } from "../../src/portfolio/live/reach.ts";
import { pick, type LiveTrader, type Market } from "../../src/portfolio/live/trade.ts";
import type { HttpReply } from "../../src/portfolio/live/types.ts";
import { json, MIN, network, NOW, venueOf, type Rec } from "./live-public-markets-fixtures.ts";

/** The IP audit's findings about the keyless public markets, the comparison, Markets, the list of where this user can connect and the terms
 * table (cluster f2, 2026-10-10): a public read blames no key, reads a ban, an edge, a redirect or a page in the venue's place as what it
 * is, keeps the hold it was given, keeps one host's refusal to that host, and names a place rule in the venue's own words where the venue
 * gives it inside its envelope. Stand-ins only — canned answers and the real exchange library fed them; nothing leaves the process, no key
 * exists here. Addresses are from the documentation ranges (RFC 5737) */
const lib = ccxt as unknown as Record<string, new (o: Record<string, unknown>) => Record<string, unknown>> & { RequestTimeout: new (m: string) => Error; BadResponse: new (m: string) => Error };
const thrown = (name: string, message: string) => Object.assign(new Error(message), { name });
const page = (status: number, text: string, more: Partial<HttpReply> = {}): HttpReply => ({ status, body: undefined, text, ...more });
const said = (r: unknown): string => String(((r as Refusal).native as { said?: unknown } | undefined)?.said ?? "");
/** CloudFront's standard geo-restriction 403 page */
const CLOUDFRONT = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1"><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY><H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">The Amazon CloudFront distribution is configured to block access from your country.<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)</PRE></BODY></HTML>`;
const BLOCK_PAGE = `<!DOCTYPE html><html><head><title>Web Page Blocked</title></head><body>Access to this site is blocked by your network administrator. Your IP: 203.0.113.9</body></html>`;

describe("a keyless read blames no key (R1-9)", () => {
  it("the exchange library's key words become the exchange refusing the request; Bybit's IP ban is a ban, held ten minutes", () => {
    const ban = exchangeNo("bybit", "Bybit", thrown("AuthenticationError", 'bybit GET https://api.bybit.com/v5/market/tickers?category=spot 200 OK {"retCode":10009,"retMsg":"IP has been banned","result":{}}'));
    expect(ban.code).toBe("E_VENUE_UNREACHABLE");
    expect(ban.message).toMatch(/has banned this machine's address/);
    expect(holdBackMs(ban)).toBeGreaterThan(9 * MIN);
    for (const err of [thrown("PermissionDenied", 'binance GET https://api.binance.com/api/v3/ticker/24hr 403 Forbidden {"code":-2010,"msg":"Not allowed."}'), thrown("AuthenticationError", 'okx GET https://www.okx.com/api/v5/market/tickers 401 Unauthorized {"code":"50110","msg":"Your IP 203.0.113.9 is not included in your API key\'s IP whitelist."}')]) {
      const r = exchangeNo("x", "X", err);
      expect(r).toMatchObject({ code: "E_VENUE_REJECTED", venue: "x", message: "X refused the request" });
      expect(r.detail).toBeUndefined();
      expect(JSON.stringify(r)).not.toMatch(/\bkey\b.*(lacks|accept)|203\.0\.113/);
    }
  });

  it("Robinhood's Stock Token list refused with a JSON 403, or in IP-list words, is the source's own refusal in keyless words", async () => {
    for (const text of ['{"detail":"Forbidden"}', '{"detail":"Request IP mismatch: IP not allowed"}']) {
      const net = network([["/rhj/assets", { status: 403, body: JSON.parse(text) as unknown, text }]]);
      const r = (await stockTokensPublic({ http: net.http, clock: () => NOW }).listings({ limit: 5 })) as Refusal;
      expect(r).toMatchObject({ code: "E_VENUE_REJECTED", venue: "robinhood-stock-tokens", message: "Robinhood Stock Tokens refused the request (HTTP 403)" });
      expect(r.detail).toBeUndefined();
      expect(r.message).not.toMatch(/key/i);
    }
  });

  it("an answer to a keyless GET is read as types.ts reads one: the venue's Retry-After, a redirect not followed, a page in the API's place, Cloudflare's text, a ban without a time", async () => {
    const one = async (reply: HttpReply): Promise<Refusal> => (await kalshiPublic({ http: network([["kalshi.com", reply]]).http, clock: () => NOW }).listings({ limit: 3 })) as Refusal;
    const slow = await one(page(429, "Too Many Requests", { retryAfterMs: 300_000 }));
    expect([slow.code, slow.message]).toEqual(["E_VENUE_UNREACHABLE", "Kalshi is rate-limiting this machine: try again in 5 minutes"]);
    expect(holdBackMs(slow)).toBeGreaterThan(4 * MIN);
    expect(await one(page(302, "", { location: "www.kalshi.com" }))).toMatchObject({ code: "E_VENUE_REJECTED", message: "Kalshi answered HTTP 302, sending the request on elsewhere: not followed" });
    const portal = await one(page(200, BLOCK_PAGE));
    expect(portal).toMatchObject({ code: "E_VENUE_UNREACHABLE", native: { status: 200, page: true } });
    expect(JSON.stringify(portal)).not.toMatch(/203\.0\.113/);
    expect(await one(page(403, "error code: 1009"))).toMatchObject({ code: "E_VENUE_GEOBLOCKED", native: { edge: true } });
    const banned = await one(page(418, '{"msg":"Way too many requests"}'));
    expect(banned).toMatchObject({ code: "E_VENUE_UNREACHABLE", native: { ban: true } });
    expect(holdBackMs(banned)).toBeGreaterThan(9 * MIN);
    // a 5xx that says how long: held that long, not 20 s
    expect(holdBackMs(await one(page(503, "Service Unavailable", { retryAfterMs: 120_000 })))).toBeGreaterThan(MIN);
  });
});

describe("one exchange's hold is only ever lengthened (R1-10)", () => {
  it("a ban answered first, then a timeout from a read sent at the same time: 21 s on, every read is still the ban, the exchange not asked", async () => {
    let now = NOW;
    const until = Date.now() + 30 * MIN;
    const pending: Array<{ resolve: () => void; reject: (e: Error) => void }> = [];
    let tickers = 0;
    const client: ExchangeClient = {
      id: "binance",
      markets: { "BTC/USDT": { symbol: "BTC/USDT", base: "BTC", quote: "USDT", spot: true }, "ETH/USDT": { symbol: "ETH/USDT", base: "ETH", quote: "USDT", spot: true }, "SOL/USDT": { symbol: "SOL/USDT", base: "SOL", quote: "USDT", spot: true } },
      async loadMarkets() {
        return this.markets;
      },
      async fetchBalance() {
        throw new Error("a public source never reads a balance");
      },
      fetchTickers() {
        tickers++;
        return new Promise((resolve, reject) => pending.push({ resolve: () => resolve({}), reject }));
      },
    };
    const open: OpenExchange = async () => client;
    const bn = exchangeTickers("binance", { open, clock: () => now });
    const a = bn.listings({ q: "btc", limit: 5 });
    const b = bn.listings({ q: "eth", limit: 5 });
    await new Promise((r) => setTimeout(r, 0));
    expect(pending).toHaveLength(2);
    pending[0]!.reject(thrown("DDoSProtection", `binance GET https://api.binance.com/api/v3/ticker/24hr 418 I'm a teapot {"code":-1003,"msg":"Way too many requests; IP banned until ${until}. Please use the websocket for live updates to avoid bans."}`));
    const ban = (await a) as Refusal;
    expect(ban).toMatchObject({ code: "E_VENUE_UNREACHABLE", native: { until } });
    pending[1]!.reject(thrown("RequestTimeout", "binance GET https://api.binance.com/api/v3/ticker/24hr request timed out (12000 ms)"));
    expect(((await b) as Refusal).code).toBe("E_VENUE_UNREACHABLE");
    now += 21_000;
    expect(await bn.listings({ q: "sol", limit: 5 })).toBe(ban);
    expect(await bn.stats!(["SOL/USDT"])).toBe(ban);
    expect(tickers).toBe(2);
  });
});

describe("a page refusing this location keeps the venue's sentence, not its markup (R1-11)", () => {
  it("CloudFront's geo page through a keyless source, and through Markets' missing", async () => {
    const http = network([["kalshi.com", page(403, CLOUDFRONT)]]).http;
    const r = (await kalshiPublic({ http, clock: () => NOW }).listings({ limit: 3 })) as Refusal;
    expect(r.code).toBe("E_VENUE_GEOBLOCKED");
    expect(said(r)).toContain("configured to block access from your country");
    expect(said(r)).not.toMatch(/<|https?:\/\//);
    const x = await exploreAcross({ public: [kalshiPublic({ http, clock: () => NOW })] }, { clock: () => NOW });
    expect(x.missing[0]!.said).toContain("configured to block access from your country");
    expect(x.missing[0]!.said).not.toMatch(/<|https?:\/\//);
  });
});

describe("a venue's no inside its own envelope (R1-39, R3-7)", () => {
  it("OKX's place rule under HTTP 200 or 403 is its place rule, held ten minutes, with no address in it; its rate limit is a wait", async () => {
    for (const [status, code, msg] of [
      [200, "50121", "You can't access our services through the IP address (203.0.113.9)"],
      [403, "50051", "Due to compliance restrictions in your country or region, you can't use this service."],
    ] as const) {
      const body = { code, msg, data: [] };
      const r = (await preIpoPublic(venueOf("okx"), { http: network([["www.okx.com", { status, body, text: JSON.stringify(body) }]]).http, clock: () => NOW }).listings({ limit: 5 })) as Refusal;
      expect(r).toMatchObject({ code: "E_VENUE_GEOBLOCKED", venue: "okx-preipo", message: "OKX does not serve this location: that is its own rule, and the account does not look for a way around it" });
      expect(holdBackMs(r)).toBe(600_000);
      expect(JSON.stringify([r.message, r.native])).not.toMatch(/203\.0\.113/);
    }
    const busy = { code: "50011", msg: "Request too frequent", data: [] };
    const r = (await preIpoPublic(venueOf("okx"), { http: network([["www.okx.com", json(busy)]]).http, clock: () => NOW }).listings({ limit: 5 })) as Refusal;
    expect(r).toMatchObject({ code: "E_VENUE_UNREACHABLE", message: "OKX is rate-limiting this machine: try again in a minute" });
  });

  it("Bybit's retCode: a place rule in its retMsg, its IP ban (10009) held ten minutes, its IP rate limit a wait; its 403 'access too frequent' a ban", async () => {
    const env = (retCode: number, retMsg: string) => json({ retCode, retMsg, result: {}, retExtInfo: {}, time: NOW });
    const ask = async (reply: HttpReply) => (await preIpoPublic(venueOf("bybit"), { http: network([["api.bybit.com", reply]]).http, clock: () => NOW }).listings({ limit: 5 })) as Refusal;
    expect((await ask(env(10024, "Service is not available in your country or region"))).code).toBe("E_VENUE_GEOBLOCKED");
    const ban = await ask(env(10009, "IP has been banned"));
    expect(ban).toMatchObject({ code: "E_VENUE_UNREACHABLE", native: { ban: true } });
    expect(holdBackMs(ban)).toBeGreaterThan(9 * MIN);
    expect(await ask(env(10018, "exceed ip rate limit"))).toMatchObject({ code: "E_VENUE_UNREACHABLE", native: { status: 429 } });
    const frequent = await ask(page(403, "403 Forbidden: access too frequent"));
    expect(frequent).toMatchObject({ code: "E_VENUE_UNREACHABLE", native: { ban: true } });
    expect(holdBackMs(frequent)).toBeGreaterThan(9 * MIN);
  });

  it("Deribit's country ban (12005 country_is_banned), under HTTP 400 or 200, is its place rule: held ten minutes, one ask across two polls; another error is a no in its own words", async () => {
    const banned = { jsonrpc: "2.0", error: { message: "country_is_banned", code: 12005 }, usIn: 1, usOut: 2 };
    for (const status of [400, 200]) {
      let now = NOW;
      const net = network([["www.deribit.com", { status, body: banned, text: JSON.stringify(banned) }]]);
      const d = preIpoPublic(venueOf("deribit"), { http: net.http, clock: () => now });
      const r = (await d.listings({ limit: 5 })) as Refusal;
      expect(r).toMatchObject({ code: "E_VENUE_GEOBLOCKED", venue: "deribit-preipo", message: "Deribit does not serve this location: that is its own rule, and the account does not look for a way around it" });
      expect(holdBackMs(r)).toBe(600_000);
      now += 5 * MIN;
      await d.listings({ limit: 5 });
      expect(net.sent).toHaveLength(1);
    }
    const other = { jsonrpc: "2.0", error: { message: "invalid_arguments", code: -32602 } };
    const r = await preIpoPublic(venueOf("deribit"), { http: network([["www.deribit.com", json(other)]]).http, clock: () => NOW }).listings({ limit: 5 });
    expect(r).toMatchObject({ code: "E_VENUE_REJECTED", message: "Deribit refused the request (invalid_arguments)" });
  });
});

describe("Binance's, Bybit's and OKX's spot tickers do not hang on their derivatives hosts (R2-6)", () => {
  it("the real library, keyless: fapi and dapi refusing this location, spot answering — spot is listed, the futures hosts never asked, nothing held", async () => {
    const sent: string[] = [];
    let made: Record<string, unknown> | undefined;
    const open: OpenExchange = async (id) => {
      const x = new lib[id]!({ apiKey: "", secret: "", enableRateLimit: false, timeout: 12_000 }) as Record<string, unknown> & { handleRestResponse: (...a: unknown[]) => Promise<unknown> };
      x.fetch = async function (url: string, method = "GET", headers: unknown = {}, body: unknown = undefined) {
        sent.push(url);
        let status = 200;
        let text: string;
        if (/fapi|dapi/.test(url)) [status, text] = [451, '{"code":0,"msg":"Service unavailable from a restricted location according to \'b. Eligibility\' in https://www.binance.com/en/terms."}'];
        else if (url.includes("/api/v3/exchangeInfo")) text = JSON.stringify({ timezone: "UTC", serverTime: NOW, symbols: [{ symbol: "BTCUSDT", status: "TRADING", baseAsset: "BTC", baseAssetPrecision: 8, quoteAsset: "USDT", quotePrecision: 8, quoteAssetPrecision: 8, orderTypes: ["LIMIT", "MARKET"], isSpotTradingAllowed: true, isMarginTradingAllowed: false, filters: [{ filterType: "PRICE_FILTER", minPrice: "0.01", maxPrice: "1000000", tickSize: "0.01" }, { filterType: "LOT_SIZE", minQty: "0.00001", maxQty: "9000", stepSize: "0.00001" }], permissions: [], permissionSets: [["SPOT"]] }] });
        else if (url.includes("ticker/24hr")) text = JSON.stringify([{ symbol: "BTCUSDT", lastPrice: "100000", bidPrice: "99999", askPrice: "100001", priceChange: "100", priceChangePercent: "0.1", quoteVolume: "123456", openTime: 0, closeTime: 1 }]);
        else [status, text] = [404, "{}"];
        const resp = { status, statusText: STATUS_CODES[status] ?? "", headers: {}, text: async () => text };
        return x.handleRestResponse(resp, url, method, headers, body);
      };
      made = x;
      return guardClient(x as unknown as ExchangeClient, lib);
    };
    const bn = exchangeTickers("binance", { open, clock: () => NOW });
    const got = (await bn.listings({ limit: 5 })) as Listing[];
    expect(got.map((m) => [m.symbol, m.price])).toEqual([["BTC/USDT", 100000]]);
    expect(sent.some((u) => /fapi|dapi/.test(u))).toBe(false);
    expect((made!.options as { fetchMarkets: { types: string[] } }).fetchMarkets.types).toEqual(["spot"]);
    // Coinbase's option is a method's name, not a list of kinds: left as it is
    const cb = new lib.coinbase!({});
    expect(typeof (cb.options as { fetchMarkets: unknown }).fetchMarkets).toBe("string");
  });
});

describe("Polymarket's history is the CLOB's, its listings Gamma's (R3-5)", () => {
  it("the source says so, and a CLOB challenge page on one chart leaves Gamma's listings asked and listed", async () => {
    const market = { conditionId: `0x${"ab".repeat(32)}`, slug: "fed-cut", question: "Fed cut?", outcomes: '["Yes","No"]', outcomePrices: '["0.4","0.6"]', clobTokenIds: '["123","456"]', active: true, closed: false, enableOrderBook: true, acceptingOrders: true, volume24hr: 1000 };
    const event = { id: "1", slug: "fed", title: "Fed", volume24hr: 1000, tags: [{ label: "Economics", slug: "economics" }], markets: [market] };
    const net = network([
      ["gamma-api.polymarket.com/markets/slug/fed-cut", json(market)],
      ["gamma-api.polymarket.com/events?", json([event])],
      ["clob.polymarket.com", page(403, "<!DOCTYPE html><html><head><title>Just a moment...</title></head><body>cf-ray</body></html>")],
    ]);
    const pm = polymarketPublic({ http: net.http, clock: () => NOW });
    expect(pm.historyApart).toBe(true);
    expect(await pm.candles!("fed-cut:Yes", "1h", NOW - 3_600_000)).toMatchObject({ code: "E_VENUE_GEOBLOCKED" });
    const listed = (await pm.listings({ limit: 5 })) as Listing[];
    expect(listed.map((l) => l.symbol)).toEqual(["fed-cut:Yes", "fed-cut:No"]);
  });
});

describe("Robinhood Stock Tokens refusing every price is the listing's answer (R3-6)", () => {
  const asset = (symbol: string): Rec => ({ id: `0x${symbol}`, tokenSymbol: symbol, tokenName: `${symbol} • Robinhood Token`, status: "ASSET_STATUS_ACTIVE", deployments: [{ contractAddress: `0x${"1".repeat(39)}${symbol.length}`, chainId: 4663 }] });
  const assets = json({ assets: [asset("AAPL"), asset("NVDA")] });
  it("a place rule, an edge page or a ban on every price: the refusal, in its words, for Markets' missing and the hold", async () => {
    for (const [reply, code] of [
      [{ status: 451, body: { detail: "Unavailable For Legal Reasons" }, text: '{"detail":"Unavailable For Legal Reasons"}' }, "E_VENUE_GEOBLOCKED"],
      [page(403, CLOUDFRONT), "E_VENUE_GEOBLOCKED"],
      [page(418, `IP banned until ${Date.now() + 20 * MIN}`), "E_VENUE_UNREACHABLE"],
    ] as const) {
      const net = network([["/rhj/assets", assets], ["/rhj/prices/", reply]]);
      const r = await stockTokensPublic({ http: net.http, clock: () => NOW }).listings({ limit: 5 });
      expect(isRefusal(r) && [r.code, r.venue]).toEqual([code, "robinhood-stock-tokens"]);
      expect(holdBackMs(r as Refusal)).toBeGreaterThan(9 * MIN);
    }
  });

  it("a price refused for one token while the other answers: that token's line says why", async () => {
    const net = network([["/rhj/assets", assets], ["/rhj/prices/AAPL", json({ quotes: [{ currency: "USD", tokenBid: "250", tokenAsk: "251", isTradingHalt: false }] })], ["/rhj/prices/NVDA", page(503, "Service Unavailable")]]);
    const got = (await stockTokensPublic({ http: net.http, clock: () => NOW }).listings({ limit: 5 })) as Listing[];
    expect(got.find((l) => l.symbol === "AAPL")).toMatchObject({ price: 250.5, open: true });
    expect(got.find((l) => l.symbol === "NVDA")).toMatchObject({ open: false, note: "Robinhood Stock Tokens did not answer" });
  });
});

/** a stand-in trader at a connected venue: lists `listed`, answers each market as listed */
function trader(listed: Market[], can: boolean | "unknown" = true): LiveTrader {
  return {
    can,
    what: "stand-in",
    markets: async (q) => pick(listed, q),
    market: async (s) => listed.find((m) => m.symbol === s)!,
    place: async () => {
      throw new Error("nothing is placed here");
    },
    cancel: async () => {
      throw new Error("nothing is cancelled here");
    },
    status: async () => {
      throw new Error("nothing is followed here");
    },
  };
}
const perp = (symbol: string, price: number): Market => ({ symbol, name: `BTC perpetual`, kind: "perp", base: "BTC", quote: "USDC", price, bid: price - 1, ask: price + 1, open: true, types: ["market", "limit"], volumeUsd24h: 1e9 });

describe("a venue whose own place rule bars this network is never 'can trade here now' (R2-7)", () => {
  const CLOSED = { rule: "closed" as const, words: "Hyperliquid does not serve this location: its Terms of Use (§1.6)" };
  const ONLY = { rule: "close-only" as const, words: "Polymarket lets this location close positions and open none" };
  const venues = (place?: CompareVenue["place"]): CompareVenue[] => [
    { id: "hyperliquid-trade", name: "Hyperliquid", trader: trader([perp("BTC-PERP", 100_000)]), ...(place ? { place } : {}) },
    { id: "other", name: "Other", trader: trader([perp("BTC/USDC:USDC", 100_050)]) },
  ];

  it("compare: a closed venue is not ready and never best, its words on the row; close-only bars a buy and leaves a sell ready", async () => {
    const free = await compareAcross(venues(), "BTC", "buy");
    expect(free.rows.find((r) => r.best)?.venue).toBe("hyperliquid-trade");
    const shut = await compareAcross(venues(CLOSED), "BTC", "buy");
    const hl = shut.rows.find((r) => r.venue === "hyperliquid-trade")!;
    expect(hl).toMatchObject({ ready: false, canTrade: false, note: CLOSED.words });
    expect(hl.best).toBeUndefined();
    expect(shut.rows.find((r) => r.best)?.venue).toBe("other");
    const buy = await compareAcross(venues(ONLY), "BTC", "buy");
    expect(buy.rows.find((r) => r.venue === "hyperliquid-trade")).toMatchObject({ ready: false, note: ONLY.words });
    const sell = await compareAcross(venues(ONLY), "BTC", "sell");
    const closing = sell.rows.find((r) => r.venue === "hyperliquid-trade")!;
    expect([closing.ready, closing.note]).toEqual([true, undefined]);
  });

  it("explore: a closed venue's lines cannot trade and say why; a close-only venue's can, and say only closing is taken", async () => {
    const at = async (place: CompareVenue["place"]) => (await exploreAcross({ connected: [{ id: "hyperliquid-trade", name: "Hyperliquid", trader: trader([perp("BTC-PERP", 100_000)]), place }] }, { clock: () => NOW })).items[0]!.at[0]!;
    expect(await at(CLOSED)).toMatchObject({ canTrade: false, note: CLOSED.words });
    expect(await at(ONLY)).toMatchObject({ canTrade: true, note: ONLY.words });
    expect(await at(undefined)).toMatchObject({ canTrade: true });
  });
});

describe("a read-by-address connection is asked like the rest (R2-25)", () => {
  const deps = (answers: Reach[]): AvailabilityDeps & { asked: string[][] } => {
    const asked: string[][] = [];
    return {
      asked,
      connections: [{ connector: "live:polymarket", name: "Polymarket · by address", group: "Markets and tokens", needs: "address" }],
      reach: async (cs) => (asked.push(cs), answers.filter((a) => cs.includes(a.connector))),
      connected: () => false,
      clock: () => NOW,
    };
  };
  it("its host refusing this network makes it not served; nothing answering for it leaves no 'asked' time", async () => {
    const at = new Date(NOW).toISOString();
    const refused = await venuesHere(deps([{ connector: "live:polymarket", state: "location", said: "Polymarket refuses this network", at }]));
    expect(refused[0]).toMatchObject({ verdict: "not-served", said: "Polymarket refuses this network", readOnly: true, asked: at });
    const d = deps([]);
    const silent = await venuesHere(d);
    expect(d.asked).toEqual([["live:polymarket"]]);
    expect(silent[0]!.verdict).toBe("connectable");
    expect(silent[0]!.asked).toBeUndefined();
  });
});

describe("Markets' notes describe only lists that answered (R4-11)", () => {
  it("a source refusing this network has no note beside its line in missing; one that answered an empty list keeps its note", async () => {
    const source = (listings: PublicSource["listings"]): PublicSource => ({ id: "s", name: "S", kind: "events", connectTo: "s", connector: "live:s", listings, notes: () => ["S: its ten busiest events."] });
    const refused = await exploreAcross({ public: [source(async () => (await kalshiPublic({ http: network([["kalshi.com", page(451, "unavailable")]]).http, clock: () => NOW }).listings({ limit: 1 })) as Refusal)] }, { clock: () => NOW });
    expect(refused.missing[0]!.code).toBe("E_VENUE_GEOBLOCKED");
    expect(refused.notes).toEqual([]);
    const empty = await exploreAcross({ public: [source(async () => [])] }, { clock: () => NOW });
    expect(empty.notes).toEqual(["S: its ten busiest events."]);
  });
});
